version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - kratos-selfservice-ui-node-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: kratos-selfservice-ui-node-{{ checksum "package-lock.json" }}
      - run: npm test

  build:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - kratos-selfservice-ui-node-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: kratos-selfservice-ui-node-{{ checksum "package-lock.json" }}
      - run: npm run build

  release:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: |
            echo 'export DOCKER_FULL_TAG=$(echo $CIRCLE_TAG | tr '+' '_')' >> $BASH_ENV
            echo 'export DOCKER_SHORT_TAG=$(echo $CIRCLE_TAG | cut -d '+' -f1)' >> $BASH_ENV
            ./.circleci/release_name.bash
            source $BASH_ENV
      - setup_remote_docker
      - run: docker build -t oryd/kratos-selfservice-ui-node:latest .
      - run:
          docker tag oryd/kratos-selfservice-ui-node:latest
          oryd/kratos-selfservice-ui-node:$DOCKER_SHORT_TAG
      - run:
          docker login --username "$DOCKER_USERNAME" --password
          "$DOCKER_PASSWORD"
      - run: docker push oryd/kratos-selfservice-ui-node:latest
      - run: docker push oryd/kratos-selfservice-ui-node:$DOCKER_SHORT_TAG

workflows:
  tbr:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
